### ISSUE TITLE
Exception 'yii\base\InvalidConfigException' with message 'Path to sitemap models "@console/models/sitemap"

### ISSUE THREAD

**Issue by sirinibin** [demisang/yii2-sitemap-generator#1]
Im getting the below  error when i run  ./yii sitemap

Exception 'yii\base\InvalidConfigException' with message 'Path to sitemap models "@console/models/sitemap"(/Applications/MAMP/htdocs/project1/app/console/models/sitemap) is incorrect'

Any idea how to fix it?

**Comment by vavilin** [comment]
the same issue, how to fix it?

**Comment by demisang** [comment]
I apologize that I did not describe how to create sitemap models :(
You should create `/console/models/sitemap` dir and put them sitemap models.

Readme updated, please read this part: https://github.com/demisang/yii2-sitemap-generator#sitemap-data-models-important

**Comment by vavilin** [comment]
@demisang Thank you for answer! :)
